### ISSUE TITLE
Does it support switching channels?

### ISSUE THREAD

**Issue by wolfg1969** [hzqtc/fmd#3]
能否加上换台的功能？还有红心频率。btw，我准备移植到openwrt上。

**Comment by hzqtc** [comment]
Yes. Command `setch` is added in recent versions but not included in the protocol document yet. Please refer to the source code (`app.c`) in the mean time. Try `fmc setch -3` to switch to Red Heart Channel.
Actually, channel number is a transparent configuration for FMD as FMD just pass the channel number in API calls. To get a complete list of channels, please refer to http://douban.fm/ and check the source code.

**Comment by hzqtc** [comment]
And feel free to use the source code. Happy hacking!
