### ISSUE TITLE
Build failed on Ubuntu 12.04

### ISSUE THREAD

**Issue by wolfg1969** [hzqtc/fmd#5]
The version of libmpg123 in Ubuntu 12.04 is 1.12.1, there is no 'mgp123_encsize' function in the mpg123.h, so I have to install the newest libmpg from source.

btw, I'm about to add a new command 'chvol' to control the volume.

**Comment by hzqtc** [comment]
Sorry for the inconvenience. I only test it on Arch and you know Arch always gets the newest version of softwares.

For the volume control thing, if can be limited within the application level (i.e. leave the system level volume unaffected), that will be nice. :)
