### ISSUE TITLE
The first "fmc toggle"

### ISSUE THREAD

**Issue by itlodge** [hzqtc/fmd#9]
I have found another problem. When I started fmd and hit "fmc toggle", the fmd was killed. And it's ok when I hit "fmc play" and then "fmc toggle". I have found the code below:
void fm_player_toggle(fm_player_t *pl)
{
    if (pl->status == FM_PLAYER_PLAY)
        fm_player_pause(pl);
    else
        fm_player_play(pl);
}
I think maybe it's where the problem occured.

**Comment by hzqtc** [comment]
I repeated your procedures and FMD worked fine. The code looks fine to me.
Also, I suggest you to check out the log and attach it here if necessary. Thanks.

**Comment by itlodge** [comment]
It's strang. Now I repeated the procedures and FMD didn't quit, but FMC didn't play.Here is the log in fmd.log:

Player audio driver: PulseAudio Output
Player sample rate: 44100 Hz
Server listen at localhost:10098
Server has a new client from 127.0.0.1:36952
Server receives from client 127.0.0.1:36952 => toggle
Player play
Playlist next song
Playlist init empty, request new
Playlist send long report: 0:n
Server says goodbye to client from 127.0.0.1:36952

**Comment by hzqtc** [comment]
It seems the API request is not responded. I update the code to log API responses. Try the new version and attach the log again. Thanks.

**Comment by itlodge** [comment]
This time FMD quit and the log is:

Player audio driver: PulseAudio Output
Player sample rate: 44100 Hz
Server listen at localhost:10098
Server has a new client from 127.0.0.1:37323
Server receives from client 127.0.0.1:37323 => toggle
Player play
Playlist next song
Playlist init empty, request new
Playlist send long report: 0:n
Playlist next song
Playlist init empty, request new
Playlist send long report: 0:n
Playlist parsing new API response

**Comment by hzqtc** [comment]
Please attach fmd.err as well.

**Comment by itlodge** [comment]
fmd.err  is empty!

**Comment by hzqtc** [comment]
I think there is something wrong with the API reponse which FMD fail to parse. But I can't debug this because I can't reproduce it. You may try printing more logs in `fm_playlist_parse_json` located in `playlist.c` to get more details.

And to make sure, this problem will not happen if you use `fmc play` instead of `fmd toggle`?

**Comment by itlodge** [comment]
Thanks, I will try to debug it.

**Comment by hzqtc** [comment]
Hi, I fixed a bug that may cause your problem. You may try the latest source and check if it's fixed. Thanks.

**Comment by itlodge** [comment]
Wow, It works!

**Comment by hzqtc** [comment]
Glad it works.
Many thanks for filing this issue.
:smiley:
